$(function(){"use strict";$('[data-toggle="tooltip"]').tooltip();$('#head_logo').append('<img src="assets/images/logo/logo.png" alt="" class="img-fluid d-block mx-auto" />');$('#foot_logo').append('<img src="assets/images/logo/logo.png" alt="" class="img-fluid d-block mx-auto mb-2" width="180" />');$('#Agent_Rera').append('Agent Rera Number : PRM/KA/RERA/1251/309/AG/220829/003073');$('#Project_Rera').append(' Project Rera : PRM/KA/RERA/1251/310/PR/040924/006989')});$(document).ready(function(){let urlString=window.location.href;$(document).ready(function(){const url=new URL(urlString);$(".website_url").val(url.href);const utm_source=url.searchParams.get('utm_source');const mainsource=url.searchParams.get('mainsource');if(utm_source){if(utm_source.toLowerCase()==='google'){var whatsappBtnDesktop=document.getElementById("discovery");if(whatsappBtnDesktop){whatsappBtnDesktop.parentNode.removeChild(whatsappBtnDesktop)}
var whatsappBtnMobile=document.getElementById("discovery_mobile");if(whatsappBtnMobile){whatsappBtnMobile.parentNode.removeChild(whatsappBtnMobile)}}else if(utm_source.toLowerCase()==='ppc'){document.getElementById('discovery').href="https://api.whatsapp.com/send?phone=917304824642&text=Hi%20I'm%20interested%20in%20Learning%20more%20About%20Godrej%20Park%20Retreat.%20Please%20Share%20Details.";document.getElementById('discovery_mobile').href="https://api.whatsapp.com/send?phone=917304824642&text=Hi%20I'm%20interested%20in%20Learning%20more%20about%20Godrej%20Park%20Retreat.%20Please%20Share%20Details."}}else if(mainsource){if(mainsource.toLowerCase().startsWith('google')){var whatsappBtnDesktop=document.getElementById("discovery");if(whatsappBtnDesktop){whatsappBtnDesktop.parentNode.removeChild(whatsappBtnDesktop)}
var whatsappBtnMobile=document.getElementById("discovery_mobile");if(whatsappBtnMobile){whatsappBtnMobile.parentNode.removeChild(whatsappBtnMobile)}}else if(mainsource.toLowerCase()==='ppc'){document.getElementById('discovery').href="https://api.whatsapp.com/send?phone=917304824642&text=Hi%20I'm%20interested%20in%20Learning%20more%20About%20Godrej%20Park%20Retreat.%20Please%20Share%20Details.";document.getElementById('discovery_mobile').href="https://api.whatsapp.com/send?phone=917304824642&text=Hi%20I'm%20interested%20in%20Learning%20more%20about%20Godrej%20Park%20Retreat.%20Please%20Share%20Details."}}});$(".custom-btn").click(function(){var myBookId=$(this).data('id');$(".form_name").val(myBookId)});$(".data-id-btn").click(function(){var myBookId=$(this).data('id');$(".form_name").val(myBookId)});$(".moreBtn").click(function(){if($(this).html()==='Read more <i class="fa fa-chevron-down"></i>'){$(this).html('Read less <i class="fa fa-chevron-up"></i>')}else{$(this).html('Read more <i class="fa fa-chevron-down"></i>')}
$(".moreText[data-hit=more"+$(this).data('target')+"]").slideToggle(500)});$(".moredisclaimerBtn").click(function(){if($(this).html()==='Read more <i class="fa fa-chevron-down"></i>'){$(this).html('Read less <i class="fa fa-chevron-up"></i>')}else{$(this).html('Read more <i class="fa fa-chevron-down"></i>')}
$(".moredisclaimerText[data-hit=more"+$(this).data('target')+"]").slideToggle(500)});if($(window).innerWidth()<576){clearInterval(formInterval)}
$(".num").on("keyup",function(e){if(this.value!=""){$(".check").prop("checked","checked")}else{$(".check").prop('checked',"")}})});function submitForm(event,formName){event.preventDefault();var formData=new FormData(document.forms[formName]);var currentUrl=window.location.href;var errorMessages=document.querySelectorAll('.error');errorMessages.forEach(function(error){error.style.display='none'});var nameValue=formData.get('name');var phoneValue=formData.get('mobile');var formnameValue=formData.get('form_name');var nameError=document.forms[formName].querySelectorAll('.error')[0];var phoneError=document.forms[formName].querySelectorAll('.error')[1];if(!nameValue&&!phoneValue){nameError.style.display='block';phoneError.style.display='block';return}
if(!nameValue){nameError.style.display='block';document.querySelectorAll('.error')[0].style.display='block';return}
if(!phoneValue){phoneError.style.display='block';return}
var form_data={name:formData.get('name'),email:formData.get('email'),mobile:formData.get('mobile'),mobile:formData.get('mobile'),form_name:formData.get('form_name'),website_url:formData.get('website_url'),currentUrl}
formData+='&currentUrl='+encodeURIComponent(currentUrl);$.ajax({type:'POST',url:'send_email.php',data:form_data,success:function(response){if(formnameValue==='Brochure'){window.location.href='thank-you?formName=Brochure'}else{window.location.href='thank-you.html'}},error:function(xhr,status,error){window.location.href='thank-you.html'}})}
